baseurl         = "https://landing-webslides.netlify.com/"
theme           = "hugo-webslides"
languageCode    = "en-us"
title           = "Drupal/WordPress CMS Department at Speed&Function"

[params]
  author = "RCJacH"
  homepage = "RCJacH.github.io"

[params.webslides]
  banner = false
  slideshow = true
  vertical =  true
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false

[blackfriday]
extensionsmask = ["autoHeaderIds"]
